# Generated by Django 4.1.2 on 2022-10-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app2',
            name='fileUploaded',
            field=models.FileField(upload_to='app2/uploaded_file'),
        ),
    ]
